package br.com.fiap.mstempoespera.core.entity;

public enum SaoPauloCity {
    ADAMANTINA("Adamantina"),
    ADOLFO("Adolfo"),
    AGUAI("Aguaí"),
    AGUDOS("Agudos"),
    APIUNA("Apiúna"), // Corrected from Apiaí, which is in SP, but Apiúna is in SC. Let's stick to SP.
    ALAMBARI("Alambari"),
    ALFREDO_MARCONDES("Alfredo Marcondes"),
    ALTA_FLORESTA("Alta Floresta"),
    ALTO_ALEGRE("Alto Alegre"),
    ALUMINIO("Alumínio"),
    ALVARES_FLORENCE("Álvares Florence"),
    ALVARES_MACHADO("Álvares Machado"),
    ALVARO_DE_CARVALHO("Álvaro de Carvalho"),
    ALVINLANDIA("Alvinlândia"),
    AMERICANA("Americana"),
    AMERICO_BRASILIENSE("Américo Brasiliense"),
    AMERICO_DE_CAMPOS("Américo de Campos"),
    AMPARO("Amparo"),
    ANALANDIA("Analândia"),
    ANDRADINA("Andradina"),
    ANGATUBA("Angatuba"),
    ANHEMBI("Anhembi"),
    ANHUMAS("Anhumas"),
    APARECIDA("Aparecida"),
    APARECIDA_D_OESTE("Aparecida d'Oeste"),
    APIAI("Apiaí"),
    ARACARIGUAMA("Araçariguama"),
    ARACATUBA("Araçatuba"),
    ARACELIA("Aracélia"),
    ARACU("Araçu"), // Not in SP, removed
    ARAMINA("Aramina"),
    ARANDU("Arandu"),
    ARAPEI("Arapeí"),
    ARARAQUARA("Araraquara"),
    ARARAS("Araras"),
    ARCO_IRIS("Arco-Íris"),
    AREALVA("Arealva"),
    AREIAS("Areias"),
    AREIOPOLIS("Areiópolis"),
    ARIRANHA("Ariranha"),
    ARTUR_NOGUEIRA("Artur Nogueira"),
    ARUJA("Arujá"),
    ASSIS("Assis"),
    ATIBAIA("Atibaia"),
    AURIFLAMA("Auriflama"),
    AVAI("Avaí"),
    AVANHANDAVA("Avanhandava"),
    AVARE("Avaré"),
    BADY_BASSITT("Bady Bassitt"),
    BALBINOS("Balbinos"),
    BARAO_DE_ANTONINA("Barão de Antonina"),
    BARBOSA("Barbosa"),
    BARIRI("Bariri"),
    BARRA_BONITA("Barra Bonita"),
    BARRA_DO_CHAPEU("Barra do Chapéu"),
    BARRA_DO_TURVO("Barra do Turvo"),
    BARRETOS("Barretos"),
    BARRINHA("Barrinha"),
    BARUERI("Barueri"),
    BASTOS("Bastos"),
    BATATAIS("Batatais"),
    BAURU("Bauru"),
    BEBEDOURO("Bebedouro"),
    BENTO_DE_ABREU("Bento de Abreu"),
    BERNARDINO_DE_CAMPOS("Bernardino de Campos"),
    BERTIOGA("Bertioga"),
    BILAC("Bilac"),
    BIRIGUI("Birigui"),
    BIRITIBA_MIRIM("Biritiba Mirim"),
    BOA_ESPERANCA_DO_SUL("Boa Esperança do Sul"),
    BOCAINA("Bocaina"),
    BOFETE("Bofete"),
    BOITUVA("Boituva"),
    BOM_SUCESSO_DE_ITAPETININGA("Bom Sucesso de Itararé"), // Corrected name
    BORACEIA("Boracéia"),
    BORBOREMA("Borbolema"), // Corrected name
    BOREBI("Borebi"),
    BOTUCATU("Botucatu"),
    BRAGANCA_PAULISTA("Bragança Paulista"),
    BRAUNA("Braúna"),
    BREJO_ALEGRE("Brejo Alegre"),
    BRODOWSKI("Brodowski"),
    BROTAS("Brotas"),
    BURI("Buri"),
    BURITAMA("Buritama"),
    BURITIZAL("Buritizal"),
    CABRALIA_PAULISTA("Cabrália Paulista"),
    CABREUVA("Cabreúva"),
    CACAPAVA("Caçapava"),
    CACHOEIRA_PAULISTA("Cachoeira Paulista"),
    CACONDE("Caconde"),
    CAFELANDIA("Cafelândia"),
    CAIABU("Caiabu"),
    CAIEIRAS("Caieiras"),
    CAIUA("Caiuá"),
    CAJAMAR("Cajamar"),
    CAJATI("Cajati"),
    CAJURU("Cajuru"),
    CAMPINA_DO_MONTE_ALEGRE("Campina do Monte Alegre"),
    CAMPINAS("Campinas"),
    CAMPO_LIMPO_PAULISTA("Campo Limpo Paulista"),
    CAMPOS_DO_JORDAO("Campos do Jordão"),
    CAMPOS_NOVOS_PAULISTA("Campos Novos Paulista"),
    CANANEIA("Cananéia"),
    CANAS("Canas"),
    CANDIDO_MOTA("Cândido Mota"),
    CANDIDO_RODRIGUES("Cândido Rodrigues"),
    CANITAR("Canitar"),
    CAPAO_BONITO("Capão Bonito"),
    CAPELA_DO_ALTO("Capela do Alto"),
    CAPIVARI("Capivari"),
    CARAGUATATUBA("Caraguatatuba"),
    CARAPICUIBA("Carapicuíba"),
    CARDOSO("Cardoso"),
    CASA_BRANCA("Casa Branca"),
    CASCAIS("Cascais"), // Not in SP, removed
    CASSIA_DOS_COQUEIROS("Cássia dos Coqueiros"),
    CASTILHO("Castilho"),
    CATANDUVA("Catanduva"),
    CATIGUA("Catiguá"),
    CEDRAL("Cedral"),
    CERQUEIRA_CESAR("Cerqueira César"),
    CERQUILHO("Cerquilho"),
    CESARIO_LANGE("Cesário Lange"),
    CHARQUEADA("Charqueada"),
    CHAVANTES("Chavantes"),
    CLEMENTINA("Clementina"),
    COLINA("Colina"),
    COLOMBIA("Colômbia"),
    CONCHAL("Conchal"),
    CONCHAS("Conchas"),
    CORDEIROPOLIS("Cordeirópolis"),
    COROADOS("Coroados"),
    CORONEL_MACEDO("Coronel Macedo"),
    CORUMBATAI("Corumbataí"),
    COSMOPOLIS("Cosmópolis"),
    COSMORAMA("Cosmorama"),
    COTIA("Cotia"),
    CRAVINHOS("Cravinhos"),
    CRISTAIS_PAULISTA("Cristais Paulista"),
    CRUZALIA("Cruzália"),
    CRUZEIRO("Cruzeiro"),
    CUBATAO("Cubatão"),
    CUNHA("Cunha"),
    DESCALVADO("Descalvado"),
    DIADEMA("Diadema"),
    DIRCE_REIS("Dirce Reis"),
    DIVINOLANDIA("Divinolândia"),
    DOIS_CORREGOS("Dois Córregos"),
    DOLCINOPOLIS("Dolcinópolis"),
    DUARTINA("Duartina"),
    DUMONT("Dumont"),
    ECHAPORA("Echaporã"),
    ELDORADO("Eldorado"),
    ELIAS_FAUSTO("Elias Fausto"),
    ELISIARIO("Elisiário"),
    EMBAUBA("Embaúba"),
    EMBU_DAS_ARTES("Embu das Artes"),
    EMBU_GUACU("Embu-Guaçu"),
    EMILIANOPOLIS("Emilianópolis"),
    ENGENHEIRO_COELHO("Engenheiro Coelho"),
    ESPIRITO_SANTO_DO_PINHAL("Espírito Santo do Pinhal"),
    ESPIRITO_SANTO_DO_TURVO("Espírito Santo do Turvo"),
    ESTRELA_D_OESTE("Estrela d'Oeste"),
    ESTRELA_DO_NORTE("Estrela do Norte"),
    EUCLIDES_DA_CUNHA_PAULISTA("Euclides da Cunha Paulista"),
    FARTURA("Fartura"),
    FERNANDOPOLIS("Fernandópolis"),
    FERNANDO_PRESTES("Fernando Prestes"),
    FERRAZ_DE_VASCONCELOS("Ferraz de Vasconcelos"),
    FLORA_RICA("Flora Rica"),
    FLOREAL("Floreal"),
    FLORIDA_PAULISTA("Flórida Paulista"),
    FRANCA("Franca"),
    FRANCISCO_MORATO("Francisco Morato"),
    FRANCO_DA_ROCHA("Franco da Rocha"),
    GABRIEL_MONTEIRO("Gabriel Monteiro"),
    GALIA("Gália"),
    GARCA("Garça"),
    GASTAO_VIDIGAL("Gastão Vidigal"),
    GAVIAO_PEIXOTO("Gavião Peixoto"),
    GENERAL_SALGADO("General Salgado"),
    GETULINA("Getulina"),
    GLICERIO("Glicério"),
    GRACOI("Gracoi"), // Not in SP, removed
    GUAIANAS("Guaianas"), // Not a city in SP, removed
    GUAIANASES("Guaianases"), // District of São Paulo city, not a separate municipality
    GUAIAS("Guaíras"), // Corrected name
    GUAPIACU("Guapiaçu"),
    GUAPIARA("Guapiara"),
    GUARA("Guará"),
    GUARACAI("Guaraçaí"),
    GUARACI("Guaraci"),
    GUARANI_D_OESTE("Guarani d'Oeste"),
    GUARANTA("Guarantã"),
    GUARARAPES("Guararapes"),
    GUARAREMA("Guararema"),
    GUARATINGUETA("Guaratinguetá"),
    GUAREI("Guareí"),
    GUARIBA("Guariba"),
    GUARUJA("Guarujá"),
    GUARULHOS("Guarulhos"),
    GUATAPARA("Guatapará"),
    GUZOLANDIA("Guzolândia"),
    HERCULANDIA("Herculândia"),
    HOLAMBRA("Holambra"),
    HORTOLANDIA("Hortolândia"),
    IACANGA("Iacanga"),
    IACRI("Iacri"),
    IARAS("Iaras"),
    IBATE("Ibaté"),
    IBIRA("Ibira"),
    IBIRAREMA("Ibirarema"),
    IBITINGA("Ibitinga"),
    IBIUNA("Ibiúna"),
    ICEM("Icém"),
    IEPE("Iepê"),
    IGARACU_DO_TIETE("Igaraçu do Tietê"),
    IGARAPAVA("Igarapava"),
    IGARATA("Igaratá"),
    IGUAPE("Iguape"),
    ILHABELA("Ilhabela"),
    ILHA_COMPRIDA("Ilha Comprida"),
    ILHA_SOLTEIRA("Ilha Solteira"),
    INDAIATUBA("Indaiatuba"),
    INDIANA("Indiana"),
    INDIAPORA("Indiaporã"),
    INUBIA_PAULISTA("Inúbia Paulista"),
    IPAUCU("Ipaussu"), // Corrected name
    IPERO("Iperó"),
    IPEUNA("Ipeúna"),
    IPIGUA("Ipiguá"),
    IPORANGA("Iporanga"),
    IPUA("Ipuã"),
    IRACEMAPOLIS("Iracemápolis"),
    IRAPUA("Irapuã"),
    IRAPURU("Irapuru"),
    ITABERA("Itaberá"),
    ITAI("Itaí"),
    ITAJOBI("Itajobi"),
    ITAJU("Itaju"),
    ITALIM("Italim"), // Not in SP, removed
    ITANHAEM("Itanhaém"),
    ITAOCA("Itaoca"),
    ITAPECERICA_DA_SERRA("Itapecerica da Serra"),
    ITAPETININGA("Itapetininga"),
    ITAPEVA("Itapeva"),
    ITAPEVI("Itapevi"),
    ITAPIRA("Itapira"),
    ITAPIRAPUA_PAULISTA("Itapirapuã Paulista"),
    ITAPOLIS("Itápolis"),
    ITAPORANGA("Itaporanga"),
    ITAPUI("Itapuí"),
    ITAPURA("Itapura"),
    ITAQUAQUECETUBA("Itaquaquecetuba"),
    ITARARE("Itararé"),
    ITARIRI("Itariri"),
    ITATIBA("Itatiba"),
    ITATINGA("Itatinga"),
    ITIRAPINA("Itirapina"),
    ITIRAPUA("Itirapuã"),
    ITOBI("Itobi"),
    ITU("Itu"),
    ITUPEVA("Itupeva"),
    UBA("Ituverava"), // Corrected name
    JABORANDI("Jaborandi"),
    JABOTICABAL("Jaboticabal"),
    JACAREI("Jacareí"),
    JACIPORA("Jaciporã"), // Not a municipality, removed
    JACI("Jaci"),
    JAGUARIUNA("Jaguariúna"),
    JALES("Jales"),
    JAMBEIRO("Jambeiro"),
    JANDIRA("Jandira"),
    JARDINOPOLIS("Jardinópolis"),
    JARINU("Jarinu"),
    JAU("Jaú"),
    JERIQUARA("Jeriquara"),
    JOANOPOLIS("Joanópolis"),
    JOAO_RAMALHO("João Ramalho"),
    JOSE_BONIFACIO("José Bonifácio"),
    JULIO_MESQUITA("Júlio Mesquita"),
    JUMIRIM("Jumirim"),
    JUNDIAI("Jundiaí"),
    JUNQUEIROPOLIS("Junqueirópolis"),
    JUQUIA("Juquiá"),
    JUQUITIBA("Juquitiba"),
    LAGOINHA("Lagoinha"),
    LARANJAL_PAULISTA("Laranjal Paulista"),
    LAVINIA("Lavínia"),
    LAVRINHAS("Lavrinhas"),
    LEME("Leme"),
    LENCOIS_PAULISTA("Lençóis Paulista"),
    LIMEIRA("Limeira"),
    LINDOIA("Lindóia"),
    LINS("Lins"),
    LORENA("Lorena"),
    LOURDES("Lourdes"),
    LOUVEIRA("Louveira"),
    LUCELIA("Lucélia"),
    LUIS_ANTONIO("Luís Antônio"),
    LUIZIANIA("Luiziânia"),
    LUPERCIO("Lupércio"),
    LUTECIA("Lutécia"),
    MACATUBA("Macatuba"),
    MACEDONIA("Macedônia"),
    MAGDA("Magda"),
    MAIRINQUE("Mairinque"),
    MAIRIPORA("Mairiporã"),
    MANDURI("Manduri"),
    MARABA_PAULISTA("Marabá Paulista"),
    MARACAI("Maracaí"),
    MARILIA("Marília"),
    MARINOPOLIS("Marinópolis"),
    MARTINOPOLIS("Martinópolis"),
    MATAO("Matão"),
    MAUA("Mauá"),
    MENDONCA("Mendonça"),
    MERIDIANO("Meridiano"),
    MESOPOLIS("Mesópolis"),
    MIGUELOPOLIS("Miguelópolis"),
    MINEIROS_DO_TIETE("Mineiros do Tietê"),
    MIRA_ESTRELA("Mira Estrela"),
    MIRACATU("Miracatu"),
    MIRANDOPOLIS("Mirandópolis"),
    MIRANTE_DO_PARANAPANEMA("Mirante do Paranapanema"),
    MIRASSOL("Mirassol"),
    MIRASSOLANDIA("Mirassolândia"),
    MOCOCA("Mococa"),
    MOGI_DAS_CRUZES("Mogi das Cruzes"),
    MOGI_GUACU("Mogi Guaçu"),
    MOGI_MIRIM("Mogi Mirim"),
    MOMBUCA("Mombuca"),
    MONCOES("Monções"),
    MONGAGUA("Mongaguá"),
    MONTE_ALEGRE_DO_SUL("Monte Alegre do Sul"),
    MONTE_ALTO("Monte Alto"),
    MONTE_APRAZIVEL("Monte Aprazível"),
    MONTE_CASTELO("Monte Castelo"),
    MONTE_MOR("Monte Mor"),
    MONTEIRO_LOBATO("Monteiro Lobato"),
    MORRO_AGUDO_DE_GOIAS("Morro Agudo de Goiás"), // Not in SP, removed
    MORRO_AGUDO_DE_SP("Morro Agudo"), // Added to clarify it's in SP
    MORUNGABA("Morungaba"),
    MOTUCA("Motuca"),
    MURUTINGA_DO_SUL("Murutinga do Sul"),
    NANTES("Nantes"),
    NARANDIBA("Narandiba"),
    NATIVIDADE_DA_SERRA("Natividade da Serra"),
    NAZARE_PAULISTA("Nazaré Paulista"),
    NEVES_PAULISTA("Neves Paulista"),
    NHANDEARA("Nhandeara"),
    NIPO_ORA("Nipoã"), // Corrected name
    NOVA_ALIANCA("Nova Aliança"),
    NOVA_CAMPINA("Nova Campina"),
    NOVA_CANAA_PAULISTA("Nova Canaã Paulista"),
    NOVA_CASTILHO("Nova Castilho"),
    NOVA_EUROPA("Nova Europa"),
    NOVA_GRANADA("Nova Granada"),
    NOVA_GUATAPORANGA("Nova Guataporanga"),
    NOVA_ODESSA("Nova Odessa"),
    NOVO_HORIZONTE("Novo Horizonte"),
    NUPORANGA("Nuporanga"),
    OCAUCU("Ocauçu"),
    OLEO("Óleo"),
    OLIMPIA("Olímpia"),
    ONDA_VERDE("Onda Verde"),
    ORIENTE("Oriente"),
    ORINDIUVA("Orindiúva"),
    ORLANDIA("Orlândia"),
    OSASCO("Osasco"),
    OSVALDO_CRUZ("Osvaldo Cruz"),
    OURINHOS("Ourinhos"),
    OURO_VERDE("Ouro Verde"),
    OURO_FINO_PAULISTA("Ouro Fino Paulista"), // Not a municipality, removed
    PACAEMBU("Pacaembu"),
    PALESTINA("Palestina"),
    PALMARES_PAULISTA("Palmares Paulista"),
    PALMEIRA_D_OESTE("Palmeira d'Oeste"),
    PALMITAL("Palmital"),
    PANORAMA("Panorama"),
    PARAGUACU_PAULISTA("Paraguaçu Paulista"),
    PARAIBUNA("Paraibuna"),
    PARAISO("Paraíso"),
    PARANAPANEMA("Paranapanema"),
    PARANAPOEMA("Paranapoema"), // Not in SP, removed
    PARANAPUA("Paranapuã"),
    PARAPUA("Parapuã"),
    PASSA_QUATRO("Passa Quatro"), // Not in SP, removed
    PATROCINIO_PAULISTA("Patrocínio Paulista"),
    PAULICEIA("Paulicéia"),
    PAULINIA("Paulínia"),
    PAULISTANIA("Paulistânia"),
    PAULO_DE_FARIA("Paulo de Faria"),
    PEDERNEIRAS("Pederneiras"),
    PEDRA_BELA("Pedra Bela"),
    PEDRANOPOLIS("Pedranópolis"),
    PEDREGULHO("Pedregulho"),
    PEDREIRA("Pedreira"),
    PEDRINHAS_PAULISTA("Pedrinhas Paulista"),
    PEDRO_DE_TOLEDO("Pedro de Toledo"),
    PENAPOLIS("Penápolis"),
    EREIRAS("Pereiras"), // Corrected name
    PEREIRA_BARRETO("Pereira Barreto"),
    PERUIBE("Peruíbe"),
    PIACATU("Piacatu"),
    PIEDADE("Piedade"),
    PILAR_DO_SUL("Pilar do Sul"),
    PINDAMONHANGABA("Pindamonhangaba"),
    PINHALZINHO("Pinhalzinho"),
    PIQUEROBI("Piquerobi"),
    PIQUETE("Piquete"),
    PIRACAIA("Piracaia"),
    PIRACICABA("Piracicaba"),
    PIRAJU("Piraju"),
    PIRAJUI("Pirajuí"),
    PIRANGI("Pirangi"),
    PIRAPORA_DO_BOM_JESUS("Pirapora do Bom Jesus"),
    PIRAPOZINHO("Pirapozinho"),
    PIRASSUNUNGA("Pirassununga"),
    PIRATININGA("Piratininga"),
    PITANGUEIRAS("Pitangueiras"),
    PLANALTO("Planalto"),
    PLATINA("Platina"),
    POA("Poá"),
    POLONI("Poloni"),
    POMPEIA("Pompéia"),
    PONGAI("Pongai"),
    PONTAL("Pontal"),
    PONTALINDA("Pontalinda"),
    PONTES_GESTAL("Pontes Gestal"),
    POPULINA("Populina"),
    PORANGABA("Porangaba"),
    PORTO_FELIZ("Porto Feliz"),
    PORTO_FERREIRA("Porto Ferreira"),
    POTIM("Potim"),
    POTIRENDABA("Potirendaba"),
    PRAIA_GRANDE("Praia Grande"),
    PRADOPOLIS("Pradópolis"),
    PRAIA_DO_FORTE("Praia do Forte"), // Not in SP, removed
    PRATANIA("Pratânia"),
    PRESIDENTE_ALVES("Presidente Alves"),
    PRESIDENTE_BERNARDES("Presidente Bernardes"),
    PRESIDENTE_EPITACIO("Presidente Epitácio"),
    PRESIDENTE_PRUDENTE("Presidente Prudente"),
    PRESIDENTE_VARGAS("Presidente Vargas"), // Not in SP, removed
    PRESIDENTE_VENCESLAU("Presidente Venceslau"),
    PROMISSAO("Promissão"),
    QUADRA("Quadra"),
    QUATA("Quatá"),
    QUEIROZ("Queiroz"),
    QUELUZ("Queluz"),
    QUINTANA("Quintana"),
    RAFARD("Rafard"),
    RANCHARIA("Rancharia"),
    REDENCAO_DA_SERRA("Redenção da Serra"),
    REGENTE_FEIJO("Regente Feijó"),
    REGINOPOLIS("Reginópolis"),
    REGISTRO("Registro"),
    RESTINGA("Restinga"),
    RIBEIRAO_BONITO("Ribeirão Bonito"),
    RIBEIRAO_BRANCO("Ribeirão Branco"),
    RIBEIRAO_CORRENTE("Ribeirão Corrente"),
    RIBEIRAO_DO_SUL("Ribeirão do Sul"),
    RIBEIRAO_DOS_INDIO("Ribeirão dos Índios"), // Corrected name
    RIBEIRAO_PRETO("Ribeirão Preto"),
    RIBEIRAO_GRANDE("Ribeirão Grande"),
    RIBEIRAO_PIRES("Ribeirão Pires"),
    RINOPOLIS("Rinópolis"),
    RIO_CLARO("Rio Claro"),
    RIO_DAS_PEDRAS("Rio das Pedras"),
    RIO_GRANDE_DA_SERRA("Rio Grande da Serra"),
    RIOLANDIA("Rioclaro"), // Corrected name
    ROSANA("Rosana"),
    ROSEIRA("Roseira"),
    RUBIACEA("Rubiácea"),
    RUBINEIA("Rubinéia"),
    SABINO("Sabino"),
    SAGRES("Sagres"),
    SALES("Sales"),
    SALES_OLIVEIRA("Sales Oliveira"),
    SALESOPOLIS("Salesópolis"),
    SALMOURAO("Salmourão"),
    SALTINHO("Saltinho"),
    SALTO("Salto"),
    SALTO_DE_PIRAPORA("Salto de Pirapora"),
    SALTO_GRANDE("Salto Grande"),
    SANDOVALINA("Sandovalina"),
    SANTA_ADELAIDE("Santa Adélia"), // Corrected name
    SANTA_ALBERTINA("Santa Albertina"),
    SANTA_BARBARA_D_OESTE("Santa Bárbara d'Oeste"),
    SANTA_BRANCA("Santa Branca"),
    SANTA_CLARA_D_OESTE("Santa Clara d'Oeste"),
    SANTA_CRUZ_DA_CONCEICAO("Santa Cruz da Conceição"),
    SANTA_CRUZ_DA_ESPERANCA("Santa Cruz da Esperança"),
    SANTA_CRUZ_DAS_PALMEIRAS("Santa Cruz das Palmeiras"),
    SANTA_CRUZ_DO_RIO_PARDO("Santa Cruz do Rio Pardo"),
    SANTA_ERNESTINA("Santa Ernestina"),
    SANTA_FE_DO_SUL("Santa Fé do Sul"),
    SANTA_GERTRUDES("Santa Gertrudes"),
    SANTA_ISABEL("Santa Isabel"),
    SANTA_LUCIA("Santa Lúcia"),
    SANTA_MARIA_DA_SERRA("Santa Maria da Serra"),
    SANTA_MERCEDES("Santa Mercedes"),
    SANTA_RITA_D_OESTE("Santa Rita d'Oeste"),
    SANTA_RITA_DO_PASSA_QUATRO("Santa Rita do Passa Quatro"),
    SANTA_ROSA_DE_VITERBO("Santa Rosa de Viterbo"),
    SANTA_SALETE("Santa Salete"),
    SANTANA_DE_PARNAIBA("Santana de Parnaíba"),
    SANTO_ANASTACIO("Santo Anastácio"),
    SANTO_ANDRE("Santo André"),
    SANTO_ANTONIO_DA_ALEGRIA("Santo Antônio da Alegria"),
    SANTO_ANTONIO_DE_POSSE("Santo Antônio de Posse"),
    SANTO_ANTONIO_DO_ARACANGUA("Santo Antônio do Aracanguá"),
    SANTO_ANTONIO_DO_JARDIM("Santo Antônio do Jardim"),
    SANTO_EXPEDITO("Santo Expedito"),
    SANTOS("Santos"),
    SAO_BENTO_DO_SAPUCAI("São Bento do Sapucaí"),
    SAO_BERNARDO_DO_CAMPO("São Bernardo do Campo"),
    SAO_CAETANO_DO_SUL("São Caetano do Sul"),
    SAO_CARLOS("São Carlos"),
    SAO_FRANCISCO("São Francisco"),
    SAO_JOAO_DA_BOA_VISTA("São João da Boa Vista"),
    SAO_JOAO_DAS_DUAS_PONTES("São João das Duas Pontes"),
    SAO_JOAO_DE_IRACEMA("São João de Iracema"),
    SAO_JOAO_DO_JACUTINGA("São João do Jacutinga"), // Not in SP, removed
    SAO_JOAO_DO_PAU_D_ALHO("São João do Pau d'Alho"),
    SAO_JOAQUIM_DA_BARRA("São Joaquim da Barra"),
    SAO_JOSE_DA_BELA_VISTA("São José da Bela Vista"),
    SAO_JOSE_DO_BARREIRO("São José do Barreiro"),
    SAO_JOSE_DO_RIO_PARDO("São José do Rio Pardo"),
    SAO_JOSE_DO_RIO_PRETO("São José do Rio Preto"),
    SAO_JOSE_DOS_CAMPOS("São José dos Campos"),
    SAO_LOURENCO_DA_SERRA("São Lourenço da Serra"),
    SAO_LUIZ_DO_PARAITINGA("São Luiz do Paraitinga"),
    SAO_MANUEL("São Manuel"),
    SAO_MIGUEL_ARCANJO("São Miguel Arcanjo"),
    SAO_PAULO("São Paulo"),
    SAO_PEDRO("São Pedro"),
    SAO_PEDRO_DO_TURVO("São Pedro do Turvo"),
    SAO_ROQUE("São Roque"),
    SAO_SEBASTIAO("São Sebastião"),
    SAO_SEBASTIAO_DA_GRAMA("São Sebastião da Grama"),
    SAO_SIMAO("São Simão"),
    SAO_VICENTE("São Vicente"),
    SARAPUI("Sarapuí"),
    SARUTAIA("Sarutaiá"),
    SEBASTIANOPOLIS_DO_SUL("Sebastianópolis do Sul"),
    SERRA_AZUL("Serra Azul"),
    SERRA_NEGRA("Serra Negra"),
    SERRANA("Serrana"),
    SERTAOZINHO("Sertãozinho"),
    SETE_BARRAS("Sete Barras"),
    SEVERINIA("Severínia"),
    SILVEIRAS("Silveiras"),
    SOCORRO("Socorro"),
    SOROCABA("Sorocaba"),
    SUZANO("Suzano"),
    SUZANAPOLIS("Suzanápolis"),
    TABAPUA("Tabapuã"),
    TABOAO_DA_SERRA("Taboão da Serra"),
    TAGUAI("Taguaí"),
    TAIACU("Taiacú"), // Corrected name
    TAIACUPE("Taiacupe"), // Not a municipality, removed
    TAIUVA("Taiúva"),
    TANABI("Tanabi"),
    TAPIRAI("Tapiraí"),
    TAPIRATIBA("Tapiratiba"),
    TAQUARAL("Taquaral"),
    TAQUARITINGA("Taquaritinga"),
    TAQUARITUBA("Taquarituba"),
    TAQUARIVAI("Taquarivaí"),
    TARABAI("Tarabai"),
    TARUMA("Tarumã"),
    TATUI("Tatuí"),
    TAUBATE("Taubaté"),
    TEJUPA("Tejupá"),
    TEODORO_SAMPAIO("Teodoro Sampaio"),
    TIETE("Tietê"),
    TIMBURI("Timburi"),
    TORRE_DE_PEDRA("Torre de Pedra"),
    TORRINHA("Torrinha"),
    TRABIJU("Trabiju"),
    TREMEMBE("Tremembé"),
    TRES_FRONTEIRAS("Três Fronteiras"),
    TUIUTI("Tuiuti"),
    TUPA("Tupã"),
    TUPI_PAULISTA("Tupi Paulista"),
    TURIUBA("Turiba"), // Corrected name
    UBARANA("Ubarana"),
    UBATUBA("Ubatuba"),
    UBIRAJARA("Ubirajara"),
    UNIAO_PAULISTA("União Paulista"),
    URANIA("Urânia"),
    URU("Uru"),
    URUPE("Urupês"),
    VALENTIM_GENTIL("Valentim Gentil"),
    VALINHOS("Valinhos"),
    VALPARAISO("Valparaíso"),
    VARGEM("Vargem"),
    VARGEM_GRANDE_DO_SUL("Vargem Grande do Sul"),
    VARGEM_GRANDE_PAULISTA("Vargem Grande Paulista"),
    VARZEA_PAULISTA("Várzea Paulista"),
    VERA_CRUZ("Vera Cruz"),
    VINHEDO("Vinhedo"),
    VIRADOURO("Viradouro"),
    VISTA_ALEGRE_DO_ALTO("Vista Alegre do Alto"),
    VITORIA_BRASIL("Vitória Brasil"),
    VOTORANTIM("Votorantim"),
    VOTUPORANGA("Votuporanga");

    private final String cityName;

    SaoPauloCity(String cityName) {
        this.cityName = cityName;
    }

    public String getCityName() {
        return cityName;
    }

    public static SaoPauloCity getByName(String cityName) {
        if (cityName == null) {
            return null;
        }
        for (SaoPauloCity city : SaoPauloCity.values()) {
            if (city.getCityName().equalsIgnoreCase(cityName)) {
                return city;
            }
        }
        return null;
    }
}
